### ISSUE TITLE
Phân công công việc cho đề tài website TMDT bán đồng phục

### ISSUE THREAD

**Issue by john9101** [john9101/project-fe-reactjs#3]
- Trang chủ, trang danh sách sản phẩm, trang chi tiết sản phẩm: @john9101 
- Trang giỏ hàng, trang thanh toán, trang liên hệ: @ThanhBinh2219 
- Trang đăng nhập, trang đăng ký, trang thông tin người dùng: @NguyenHoangAnhDuong 

> [!WARNING]  
> Các thành viên không push code trực tiếp vào main, sử dụng **pull request** để merge vào main và người tạo **pull request** phải đợi các thành viên khác **review đầy đủ** và **approve** thì mới được merge 

> [!IMPORTANT]  
> - Đặt tên branch theo chức năng/trang kiểu **camel case** và để **tiếng anh**
> - Các thanh viên phải hiện thực code UI phải đồng nhất font chữ, color và theme của template
> - Các thành hiện thực code UI viết hoàn toàn bằng **typescript** và tạo component bằng **function component** (trong trường **function component** không phục vụ tốt thì mới đổi qua _class component_)

> [!NOTE]  
> Trong dựa án sẽ sử dụng API được tạo thông qua **JSON SERVER** và call API bằng cách sử dựng **fetch** hoặc **axios**. Nên tất cả các thành viên phải tìm hiểu **JSON SERVER** và cách sử dủng **fetch** và async/await

**Github JSON SERVER:** https://github.com/typicode/json-server
**Github axios:** https://github.com/axios/axios

**Comment by BrianNguyen22** [comment]
ok

**Comment by NguyenHoangAnhDuong** [comment]
ok

**Comment by NguyenHoangAnhDuong** [comment]
ok

**Comment by NguyenHoangAnhDuong** [comment]
ok
